/**
 * Merges default translations with optional overrides and writes src/i18n/generated/*.merged.ts for Astro build.
 *
 * **Sources of overrides (choose one per deployment; do not mix without a policy):**
 * - **Git / Decap:** Committed [`i18n-overrides.json`](../i18n-overrides.json) deep-merged last (after defaults).
 * - **DynamoDB (AWS admin):** CI may run `fetch:i18n` before merge, which overwrites that JSON in the workspace only — see `.github/workflows/deploy-site.yml` and repo variable `SKIP_FETCH_I18N`.
 * - **Local:** Same file, or `I18N_OVERRIDES_JSON` / `I18N_OVERRIDES_PATH`.
 */
import { mkdirSync, readFileSync, writeFileSync, existsSync } from 'node:fs';
import { join } from 'node:path';
import { mergeDeep } from './merge-deep';
import type { Translations } from '../src/i18n/es';
import { es as esDefault } from '../src/i18n/es';
import { en as enDefault } from '../src/i18n/en';

const root = process.cwd();
const outDir = join(root, 'src/i18n/generated');

type OverridesFile = { es?: unknown; en?: unknown };

function loadOverrides(): OverridesFile {
  const jsonEnv = process.env.I18N_OVERRIDES_JSON;
  if (jsonEnv) {
    try {
      return JSON.parse(jsonEnv) as OverridesFile;
    } catch (e) {
      console.warn('Invalid I18N_OVERRIDES_JSON:', e);
    }
  }
  const path = process.env.I18N_OVERRIDES_PATH ?? join(root, 'i18n-overrides.json');
  if (existsSync(path)) {
    const raw = readFileSync(path, 'utf8');
    return JSON.parse(raw) as OverridesFile;
  }
  return {};
}

function emitLocaleFile(
  name: 'es' | 'en',
  merged: Translations,
): void {
  const body = `/* eslint-disable */
// Generated by scripts/merge-i18n.ts — do not edit by hand
import type { Translations } from '../es';
export const ${name} = ${JSON.stringify(merged, null, 2)} as unknown as Translations;
`;
  writeFileSync(join(outDir, `${name}.merged.ts`), body, 'utf8');
}

mkdirSync(outDir, { recursive: true });

const overrides = loadOverrides();
const esMerged = mergeDeep(esDefault as unknown as Translations, overrides.es ?? {});
const enMerged = mergeDeep(enDefault as unknown as Translations, overrides.en ?? {});

emitLocaleFile('es', esMerged);
emitLocaleFile('en', enMerged);

console.log('Wrote src/i18n/generated/es.merged.ts and en.merged.ts');
